# Generated by Django 4.1.6 on 2023-02-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', '$'), ('rub', '₽')], default='usd', max_length=20),
        ),
    ]
